# Generated by Django 4.0.5 on 2023-01-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeusers',
            old_name='user',
            new_name='active_users',
        ),
    ]
